### ISSUE TITLE
REST output should be consistent

### ISSUE THREAD

**Issue by tyler-johnson** [BeneathTheInk/couchdb-jwt-auth-server#14]
The REST endpoints lack any kind of consistent behavior currently and this will make it harder for clients to integrate with it.
- Server should output JSON errors with clear types. The jsonwebtoken library already does a good job with this, so this will be very straight forward.
- Server should output the same Content-Type for every endpoint by default, probably JSON. The `application/jwt` type could still be produced, but only when the request has it marked in the `Accept` header.

**Comment by dariocravero** [comment]
Sounds good to me :)
